package ConsoleCommands;

public enum CommandList {
    ADD_PATIENT,
    CHANGE_PATIENT,
    DELETE_PATIENT,
    ADD_DOCTOR,
    CHANGE_DOCTOR,
    DELETE_DOCTOR,
    ADD_APPOINTMENT,
    CHANGE_APPOINTMENT_STATUS,
    DELETE_APPOINTMENT,
    DISPLAY_APPOINTMENTS,
    DISPLAY_PATIENTS,
    DISPLAY_DOCTORS,
    EXIT,
    UNDEFINED
}
